spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver-class-name}
  profiles:
    active: ${APP_PROFILE:prod}

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health" ]
    health:
      show-details: always
      sensitive: false
      defaults:
        enabled: true
      db:
        enabled:true

payment:
  url: ${production.url}