spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver-class-name}
  profiles:
    active: ${APP_PROFILE:prod}
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health" ]
    health:
      show-details: always
      sensitive: false
      defaults:
        enabled: true
      db:
        enabled:true

payment:
  url: ${production.url}
production:
  url: ${production.url}

messaging:
  output: "arn:aws:sns:us-east-1:027260563052:created_orders_topic"
