database:
  username: techfood
  password: techfood
  url: jdbc:mysql://db:3306/techfood
  driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

payment:
  url: "http://techfood-ms-payment-app-1:8081/payment/generate"